- name: Config file
  ansible.builtin.set_fact:
    config_remote_file: "{{ '~/libvirt/' + fqdn + '.xml' }}"

- name: Read the remote machine's config
  ansible.builtin.slurp:
    src: "{{ config_remote_file }}"
  register: r_slurp

- name: Decode VM config
  ansible.builtin.set_fact:
    config_xml: "{{ r_slurp['content'] | b64decode }}"

- name: Display VM config
  ansible.builtin.debug:
    msg: "{{ config_xml }}"
    verbosity: 1

